services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.multistage
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: yt_fetch
      YT_API_KEY: ${YT_API_KEY}
    ports:
      - "1234:1234"
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

volumes:
  db-data:
